# Splunk indexes.conf
# Deploy to: $SPLUNK_HOME/etc/system/local/indexes.conf (on Splunk server)

[endpoint]
homePath = $SPLUNK_DB/endpoint/db
coldPath = $SPLUNK_DB/endpoint/colddb
thawedPath = $SPLUNK_DB/endpoint/thaweddb
maxTotalDataSizeMB = 5000
frozenTimePeriodInSecs = 2592000

[wineventlog]
homePath = $SPLUNK_DB/wineventlog/db
coldPath = $SPLUNK_DB/wineventlog/colddb
thawedPath = $SPLUNK_DB/wineventlog/thaweddb
maxTotalDataSizeMB = 10000
frozenTimePeriodInSecs = 2592000
