# Splunk Universal Forwarder inputs.conf
# Deploy to: C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf
# On: WIN10-VICTIM and Windows Server DC

[WinEventLog://Security]
index = wineventlog
disabled = 0
start_from = oldest
current_only = 0
evt_resolve_ad_obj = 1
checkpointInterval = 5

[WinEventLog://System]
index = wineventlog
disabled = 0
start_from = oldest

[WinEventLog://Application]
index = wineventlog
disabled = 0
start_from = oldest

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = endpoint
disabled = 0
renderXml = true
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
index = endpoint
disabled = 0
renderXml = true
source = XmlWinEventLog:Microsoft-Windows-PowerShell/Operational

[WinEventLog://Microsoft-Windows-Windows Defender/Operational]
index = endpoint
disabled = 0
